# Generated by Django 4.0.3 on 2022-03-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='employes',
        ),
        migrations.DeleteModel(
            name='Employes',
        ),
    ]
